<?php

namespace AppBundle\Repository;

/**
 * ProcessRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProcessRepository extends \Doctrine\ORM\EntityRepository
{
    public function filterByDate($beginDate, $endDate)
    {
        $qb = $this->createQueryBuilder('p')
                ->where("p.date > :beginDate")
                ->andWhere("p.date < :endDate")
                ->setParameter('beginDate', $beginDate)
                ->setParameter('endDate', $endDate);

        $query = $qb->getQuery();

        return $query->getResult();
    }
}
